/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCMINER_H_RPCGEN
#define _RPCMINER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct row {
	int status;
	int challenge;
	char seed[40];
};
typedef struct row row;

struct challengeTuple {
	int transactionId;
	int clientID;
	char seed[40];
};
typedef struct challengeTuple challengeTuple;

#define PROG 666
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define GETTRANSACTIONID 1
extern  int * gettransactionid_100(void *, CLIENT *);
extern  int * gettransactionid_100_svc(void *, struct svc_req *);
#define GETCHALLENGE 2
extern  int * getchallenge_100(int *, CLIENT *);
extern  int * getchallenge_100_svc(int *, struct svc_req *);
#define GETTRANSACTIONSTATUS 3
extern  int * gettransactionstatus_100(int *, CLIENT *);
extern  int * gettransactionstatus_100_svc(int *, struct svc_req *);
#define SUBMITCHALLENGE 4
extern  int * submitchallenge_100(challengeTuple *, CLIENT *);
extern  int * submitchallenge_100_svc(challengeTuple *, struct svc_req *);
#define GETWINNER 5
extern  int * getwinner_100(int *, CLIENT *);
extern  int * getwinner_100_svc(int *, struct svc_req *);
#define GETSEED 6
extern  row * getseed_100(int *, CLIENT *);
extern  row * getseed_100_svc(int *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETTRANSACTIONID 1
extern  int * gettransactionid_100();
extern  int * gettransactionid_100_svc();
#define GETCHALLENGE 2
extern  int * getchallenge_100();
extern  int * getchallenge_100_svc();
#define GETTRANSACTIONSTATUS 3
extern  int * gettransactionstatus_100();
extern  int * gettransactionstatus_100_svc();
#define SUBMITCHALLENGE 4
extern  int * submitchallenge_100();
extern  int * submitchallenge_100_svc();
#define GETWINNER 5
extern  int * getwinner_100();
extern  int * getwinner_100_svc();
#define GETSEED 6
extern  row * getseed_100();
extern  row * getseed_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_row (XDR *, row*);
extern  bool_t xdr_challengeTuple (XDR *, challengeTuple*);

#else /* K&R C */
extern bool_t xdr_row ();
extern bool_t xdr_challengeTuple ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCMINER_H_RPCGEN */
