/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcMiner.h"

bool_t
xdr_row (XDR *xdrs, row *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->challenge))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->seed, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_challengeTuple (XDR *xdrs, challengeTuple *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->transactionId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->clientID))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->seed, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
